### ISSUE TITLE
Memory/recall database with previous experiences (successes, failures, solutions, ...)

### ISSUE THREAD

**Issue by maciejmajek** [RobotecAI/rai#165]
**Is your feature request related to a problem? Please describe.**
The agent can retrieve valuable information from past experiences (e.g., failures, successes, solutions, etc.) using n-shot or fine-tuning. Without the ability to train the model or search for similar problems during runtime, the agent may end up solving the same set of problems repeatedly.

**Describe the solution you'd like**
Database storing previous experiences. 
Problem example:
There is a problem with robot's navigation. The robot can't reach the final position.
Agent reasons and finds the solution in 10 steps, which took considerable amount of time.

The problem could be added to the db as:
```yaml
problem:
 title: nav2 problem, can't reach the final step
 description: ...
 solution: ...
```
